name: tallysheet_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  intl: ^0.17.0
  
  firebase_core: ^3.1.1
  firebase_database: ^11.0.1
  cloud_firestore: ^5.0.2
  
  # Thêm nhiều nút con phía dưới màn hình
  flutter_speed_dial: ^6.0.0

  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/tallysheet.png"